# Generated by Django 5.1.7 on 2025-05-08 20:07

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_journal_alter_portfolioimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='full_content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
