# Generated by Django 5.1.7 on 2025-05-10 10:59

import django_ckeditor_5.fields
import furniture.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_alter_journal_full_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=furniture.models.journal_image_path)),
                ('category', models.CharField(choices=[('inspiration', 'Inspiration'), ('tutorials', 'Tutorials'), ('updates', 'Updates')], max_length=20)),
                ('excerpt', models.TextField(max_length=500)),
                ('full_content', django_ckeditor_5.fields.CKEditor5Field()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
