# Generated by Django 5.1.7 on 2025-05-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0004_journalentry_delete_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='furniture_j_date_26d638_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['category'], name='furniture_j_categor_21b806_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['popularity'], name='furniture_p_popular_0433e9_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioitem',
            index=models.Index(fields=['created_at'], name='furniture_p_created_30bc4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='portfolioimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('portfolio_item', 'is_primary'), name='unique_primary_image_per_portfolio'),
        ),
    ]
