# Generated by Django 5.1.7 on 2025-05-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0007_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
